
CREATE VIEW total_sales_by_store_month AS
SELECT STORE_ID, BUSINESS_MONTH, TOTAL_SALES
FROM LZ_Foods;


CREATE VIEW sales_by_delivery_channel AS
SELECT STORE_ID, BUSINESS_MONTH, 
       DELIVERY_SALES, NON_DELIVERY_SALES,
       SWIGGY_DELIVERY_SALES, ZOMATO_DELIVERY_SALES, AMAZON_FOODS_DELIVERY_SALES,
       GPAY_DELIVERY_SALES, PAYTM_MICROAPP_DELIVERY_SALES,
       PHONE_DELIVERY_SALES, CALL_CENTER_DELIVERY_SALES,
       DINEIN_CHANNEL_SALES, ODC_DINEIN_SALES, KIOSK_DINEIN_SALES
FROM LZ_Foods;

CREATE VIEW orders_by_delivery_channel AS
SELECT STORE_ID, BUSINESS_MONTH, 
       DELIVERY_ORDER, NON_DELIVERY_ORDER,
       SWIGGY_DELIVERY_ORDER, ZOMATO_DELIVERY_ORDER, AMAZON_FOODS_DELIVERY_ORDER,
       GPAY_DELIVERY_ORDER, PAYTM_MICROAPP_DELIVERY_ORDER,
       PHONE_DELIVERY_ORDER, CALL_CENTER_DELIVERY_ORDER,
       DINEIN_CHANNEL_ORDER, ODC_DINEIN_ORDER, KIOSK_DINEIN_ORDER
FROM LZ_Foods;

CREATE VIEW sales_distribution_by_channel_type AS
SELECT STORE_ID, BUSINESS_MONTH,
       DELIVERY_SALES, DINEIN_SALES, TAKEAWAY_SALES
FROM LZ_Foods;

CREATE VIEW avg_order_value_by_channel AS
SELECT STORE_ID, BUSINESS_MONTH,
       DELIVERY_SALES / NULLIF(DELIVERY_ORDER, 0) AS AVG_DELIVERY_ORDER_VALUE,
       DINEIN_SALES / NULLIF(DINEIN_ORDER, 0) AS AVG_DINEIN_ORDER_VALUE,
       TAKEAWAY_SALES / NULLIF(TAKEAWAY_ORDER, 0) AS AVG_TAKEAWAY_ORDER_VALUE
FROM LZ_Foods
WHERE DELIVERY_ORDER > 0 AND DINEIN_ORDER > 0 AND TAKEAWAY_ORDER > 0;

CREATE VIEW BusinessMonthView AS
SELECT 
    BUSINESS_MONTH,
    CASE 
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 1 THEN 'January'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 2 THEN 'February'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 3 THEN 'March'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 4 THEN 'April'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 5 THEN 'May'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 6 THEN 'June'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 7 THEN 'July'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 8 THEN 'August'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 9 THEN 'September'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 10 THEN 'October'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 11 THEN 'November'
        WHEN EXTRACT(MONTH FROM BUSINESS_MONTH) = 12 THEN 'December'
    END AS MONTH_NAME,
    CASE 
        WHEN EXTRACT(QUARTER FROM BUSINESS_MONTH) = 1 THEN 'Q1'
        WHEN EXTRACT(QUARTER FROM BUSINESS_MONTH) = 2 THEN 'Q2'
        WHEN EXTRACT(QUARTER FROM BUSINESS_MONTH) = 3 THEN 'Q3'
        WHEN EXTRACT(QUARTER FROM BUSINESS_MONTH) = 4 THEN 'Q4'
    END AS QUARTER_NAME,
    EXTRACT(YEAR FROM BUSINESS_MONTH) AS YEAR,
    TO_CHAR(BUSINESS_MONTH, 'Month YYYY') AS MONTH_YEAR_FORMAT
FROM LZ_Foods;
